[project]
name = "japanese-holiday-calendar"
version = "0.1.0"
description = "MCP server for Japanese holiday calendar information"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.3",
]
